# Generated by Django 4.2 on 2025-02-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="transactinal_key",
            new_name="transactional_key",
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cc", "Cedula ciudadania"),
                    ("ce", "Cedula Extrajera"),
                    ("pp", "Pasaporte"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
