# Generated by Django 4.2 on 2025-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_is_active_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
