# Generated by Django 4.2 on 2025-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("i", "inactive"), ("a", "active"), ("c", "cancel")],
                default="a",
                max_length=1,
            ),
        ),
    ]
